version: "3"

services:
  web:
    build: .
    command: bash -c "sleep 10 && python manage.py runserver 0.0.0.0:8000" # для синхронизации с бд
    volumes:
      - avatars:/path/to/avatars
      - manga_images:/path/to/manga_image
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}


volumes:
  pg_data:
  avatars:
  manga_images:
