# Generated by Django 4.2.4 on 2023-08-05 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_alter_manga_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manga',
            options={'ordering': ['id'], 'verbose_name': 'manga', 'verbose_name_plural': 'manga'},
        ),
    ]
