# Generated by Django 4.2.4 on 2023-08-05 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'review', 'verbose_name_plural': 'reviews'},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='image',
            new_name='photo',
        ),
    ]
