# Generated by Django 4.2.4 on 2023-08-05 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_options_rename_image_review_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='photo',
            new_name='avatar',
        ),
    ]
